-- vhdl entity raro_ikr_risc_ii_lib.alu_ex.interface
--
-- created:
--          by - lspetrck.meyer (pc091)
--          at - 17:04:37 05/25/22
--
-- generated by mentor graphics' hdl designer(tm) 2020.2 built on 12 apr 2020 at 11:28:22
--
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
library raro_ikr_risc_ii_lib;
use raro_ikr_risc_ii_lib.isa_types.all;
use raro_ikr_risc_ii_lib.internal_types.all;

entity alu_ex is
   port( 
      mux_alu_a    : in     word;
      mux_alu_b    : in     word;
      ralumode_out : in     alu_mode_type;
      alu_out      : out    word
   );

-- declarations

end alu_ex ;

