-- VHDL Entity raro_ikr_risc_II_lib.ALU_ex.generatedInstance
--
-- Created:
--          by - lspetrck.meyer (pc091)
--          at - 17:20:48 05/18/22
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2020.2 Built on 12 Apr 2020 at 11:28:22
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;

ENTITY ALU_ex IS
   PORT( 
      ALU_out : OUT    std_logic_vector (15 DOWNTO 0)
   );

END ALU_ex ;

