--
-- lovingly generated by rasm 2022-06-15 14:02
-- on wed jul 13 15:33:49 cest 2022
--
-- input file:
--   /u/home/stud/kntntply/documents/raro_ikr_risc_ii/raro_ikr_risc_ii/raro_ikr_risc_ii_lib/hdl/branchin_test.rasm
-- ouput file: 
--   /u/home/stud/kntntply/documents/raro_ikr_risc_ii/raro_ikr_risc_ii/raro_ikr_risc_ii_lib/hdl/branchin_test_pkg.vhd
--
library ieee;
use ieee.std_logic_1164.all;

package mem_contents is
constant mem_depth : integer := 1024;
constant mem_width : integer := 32;
type mem_content_type is array (0 to mem_depth - 1) of std_logic_vector(mem_width - 1 downto 0);
constant mem_content : mem_content_type := (
    16#0# => x"00200005",
    16#1# => x"01600001",
    16#2# => x"01400006",
    16#3# => x"fc40080a",
    16#4# => x"fc612002",
    16#5# => x"fc812402",
    16#6# => x"f400000d",
    16#7# => x"f800000b",
    16#8# => x"f400000b",
    16#9# => x"f8440009",
    16#a# => x"f4000009",
    16#b# => x"f8680007",
    16#c# => x"f4000007",
    16#d# => x"f86c0005",
    16#e# => x"f4000005",
    16#f# => x"f8500003",
    16#10# => x"f4000003",
    16#11# => x"f8740001",
    16#12# => x"f4000001",
    16#13# => x"ffff000b",
    16#14# => x"fc1ff000",
    16#15# => x"01400006",
    others => x"00000000" );

  constant mem_used : positive := 22;
end mem_contents;
