-- vhdl entity raro_ikr_risc_ii_lib.clk_res_gen.interface
--
-- created:
--          by - lspetrck.meyer (pc091)
--          at - 17:40:31 05/11/22
--
-- generated by mentor graphics' hdl designer(tm) 2020.2 built on 12 apr 2020 at 11:28:22
--
library ieee;
use ieee.std_logic_1164.all;

library raro_ikr_risc_ii_lib;
use raro_ikr_risc_ii_lib.internal_types.all;

entity clk_res_gen is
   port( 
      res_n   : out    std_logic;
      std_clk : out    std_logic
   );

-- declarations

end clk_res_gen ;

