-- VHDL Entity raro_ikr_risc_II_lib.clk_res_gen.interface
--
-- Created:
--          by - lspetrck.meyer (pc091)
--          at - 17:40:31 05/11/22
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2020.2 Built on 12 Apr 2020 at 11:28:22
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;

ENTITY clk_res_gen IS
   PORT( 
      clk   : OUT    std_logic;
      res_n : OUT    std_logic
   );

-- Declarations

END clk_res_gen ;

