-- VHDL Entity raro_ikr_risc_II_lib.dbpu.generatedInstance
--
-- Created:
--          by - kntntply.meyer (pc091)
--          at - 16:15:37 07/13/22
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2020.2 Built on 12 Apr 2020 at 11:28:22
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;
LIBRARY raro_ikr_risc_II_lib;
USE raro_ikr_risc_II_lib.internal_types.all;USE raro_ikr_risc_II_lib.isa_types.ALL;

ENTITY dbpu IS
   PORT( 
      dbpu_PC        : OUT    word;
      dbta_valid     : OUT    std_logic;
      mux_ALU_B      : IN     word;
      rDbpu_mode_out : IN     dbpu_mode_type;
      rSbpu_PC_out   : IN     word;
      rStoreData_in  : IN     word;
      sel_ALU_PC     : OUT    std_logic
   );

END dbpu ;

