-- VHDL Entity raro_ikr_risc_II_lib.DEC_dc.interface
--
-- Created:
--          by - lspetrck.meyer (pc086)
--          at - 17:47:04 05/24/22
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2020.2 Built on 12 Apr 2020 at 11:28:22
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
LIBRARY raro_ikr_risc_II_lib;
USE raro_ikr_risc_II_lib.internal_types.ALL;
USE raro_ikr_risc_II_lib.isa_types.ALL;

ENTITY DEC_dc IS
   PORT( 
      rOpcode_out : IN     word;
      a_imm       : OUT    word;
      rAluMode_in : OUT    alu_mode_type;
      sel_a       : OUT    std_logic_vector (4 DOWNTO 0);
      sel_b       : OUT    std_logic_vector (4 DOWNTO 0);
      sel_c       : OUT    std_logic_vector (4 DOWNTO 0);
      sel_imm     : OUT    std_logic
   );

-- Declarations

END DEC_dc ;

