-- vhdl entity raro_ikr_risc_ii_lib.dec_dc.interface
--
-- created:
--          by - lspetrck.meyer (pc091)
--          at - 14:58:35 06/15/22
--
-- generated by mentor graphics' hdl designer(tm) 2020.2 built on 12 apr 2020 at 11:28:22
--
library ieee;
use ieee.std_logic_1164.all;
library raro_ikr_risc_ii_lib;
use raro_ikr_risc_ii_lib.internal_types.all;
use raro_ikr_risc_ii_lib.isa_types.all;

entity dec_dc is
   port( 
      dbta_valid        : in     std_logic;
      rmemmode_out_ex   : in     mem_mode_type;
      ropcode_out       : in     word;
      rtargetreg_out_ex : in     reg_addr_type;
      rtargetreg_out_me : in     reg_addr_type;
      a_imm             : out    word;
      disp              : out    word;
      ralumode_in       : out    alu_mode_type;
      rdbpu_mode_in     : out    dbpu_mode_type;
      rfwd_sela_in_dc   : out    fwd_mode_type;
      rfwd_selb_in_dc   : out    fwd_mode_type;
      rfwd_selc_in_dc   : out    fwd_mode_type;
      rfwd_selsd_in_dc  : out    fwd_mode_type;
      rmemmode_in_dc    : out    mem_mode_type;
      rtargetreg_in_dc  : out    reg_addr_type;
      sbpu_mode         : out    sbpu_mode_type;
      sel_a             : out    reg_addr_type;
      sel_b             : out    reg_addr_type;
      sel_c             : out    reg_addr_type;
      sel_imm           : out    std_logic;
      stall_dc          : out    std_logic
   );

-- declarations

end dec_dc ;

