-- vhdl entity raro_ikr_risc_ii_lib.man_clk_sim.generatedinstance
--
-- created:
--          by - kntntply.meyer (pc091)
--          at - 17:31:49 07/13/22
--
-- generated by mentor graphics' hdl designer(tm) 2020.2 built on 12 apr 2020 at 11:28:22
--
library ieee;
use ieee.std_logic_1164.all;

library raro_ikr_risc_ii_lib;
use raro_ikr_risc_ii_lib.internal_types.all;

entity man_clk_sim is
   port( 
      man_clk : out    std_logic;
      sel_clk : out    std_logic
   );

end man_clk_sim ;

