-- VHDL Entity raro_ikr_risc_II_lib.man_clk_sim.interface
--
-- Created:
--          by - kntntply.meyer (pc091)
--          at - 14:40:20 07/13/22
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2020.2 Built on 12 Apr 2020 at 11:28:22
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;

LIBRARY raro_ikr_risc_II_lib;
USE raro_ikr_risc_II_lib.internal_types.ALL;

ENTITY man_clk_sim IS
   PORT( 
      man_clk : OUT    std_logic;
      sel_clk : OUT    std_logic
   );

-- Declarations

END man_clk_sim ;

