-- vhdl entity raro_ikr_risc_ii_lib.mux_ex_3.interface
--
-- created:
--          by - kntntply.meyer (pc091)
--          at - 16:00:32 06/22/22
--
-- generated by mentor graphics' hdl designer(tm) 2020.2 built on 12 apr 2020 at 11:28:22
--
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
library raro_ikr_risc_ii_lib;
use raro_ikr_risc_ii_lib.isa_types.all;
use raro_ikr_risc_ii_lib.internal_types.all;

entity mux_ex_3 is
   port( 
      ralu_out         : in     word;
      rc_out           : in     word;
      rfwd_selc_out_ex : in     fwd_mode_type;
      rme_out          : in     word;
      rstoredata_in    : out    word
   );

-- declarations

end mux_ex_3 ;

