-- VHDL Entity raro_ikr_risc_II_lib.mux_init.interface
--
-- Created:
--          by - lspetrck.meyer (pc091)
--          at - 18:20:46 05/11/22
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2020.2 Built on 12 Apr 2020 at 11:28:22
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
LIBRARY raro_ikr_risc_II_lib;
USE raro_ikr_risc_II_lib.internal_types.all;

ENTITY mux_init IS
   PORT( 
      if_out_rPc : IN     word;
      if_in_rPc  : OUT    word
   );

-- Declarations

END mux_init ;

