-- vhdl entity raro_ikr_risc_ii_lib.mux_ex_2.interface
--
-- created:
--          by - lspetrck.meyer (pc091)
--          at - 12:08:28 06/15/22
--
-- generated by mentor graphics' hdl designer(tm) 2020.2 built on 12 apr 2020 at 11:28:22
--
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
library raro_ikr_risc_ii_lib;
use raro_ikr_risc_ii_lib.isa_types.all;
use raro_ikr_risc_ii_lib.internal_types.all;

entity mux_ex_2 is
   port( 
      ralu_out         : in     word;
      rb_out           : in     word;
      rfwd_selb_out_ex : in     fwd_mode_type;
      rme_out          : in     word;
      mux_alu_b        : out    word
   );

-- declarations

end mux_ex_2 ;

