-- VHDL Entity raro_ikr_risc_II_lib.MUX_dc.generatedInstance
--
-- Created:
--          by - lspetrck.meyer (pc091)
--          at - 16:56:14 05/18/22
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2020.2 Built on 12 Apr 2020 at 11:28:22
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
LIBRARY raro_ikr_risc_II_lib;
USE raro_ikr_risc_II_lib.internal_types.ALL;
USE raro_ikr_risc_II_lib.isa_types.ALL;

ENTITY MUX_dc IS
   PORT( 
      a_imm    : IN     word;
      rA_in    : OUT    word;
      rf_mux_a : IN     word
   );

END MUX_dc ;

