-- VHDL Entity raro_ikr_risc_II_lib.MUX_ex_4.interface
--
-- Created:
--          by - lspetrck.meyer (pc086)
--          at - 18:01:05 05/24/22
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2020.2 Built on 12 Apr 2020 at 11:28:22
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;
LIBRARY raro_ikr_risc_II_lib;
USE raro_ikr_risc_II_lib.isa_types.ALL;
USE raro_ikr_risc_II_lib.internal_types.ALL;

ENTITY MUX_ex_4 IS
   PORT( 
      ALU_out        : IN     word;
      rNextPC_out_ex : IN     word;
      sel_ALU_PC     : IN     std_logic;
      rALU_in        : OUT    word
   );

-- Declarations

END MUX_ex_4 ;

