-- vhdl entity raro_ikr_risc_ii_lib.mux_ex_4.interface
--
-- created:
--          by - lspetrck.meyer (pc086)
--          at - 18:01:05 05/24/22
--
-- generated by mentor graphics' hdl designer(tm) 2020.2 built on 12 apr 2020 at 11:28:22
--
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
library raro_ikr_risc_ii_lib;
use raro_ikr_risc_ii_lib.isa_types.all;
use raro_ikr_risc_ii_lib.internal_types.all;

entity mux_ex_4 is
   port( 
      alu_out        : in     word;
      rnextpc_out_ex : in     word;
      sel_alu_pc     : in     std_logic;
      ralu_in        : out    word
   );

-- declarations

end mux_ex_4 ;

