-- vhdl entity raro_ikr_risc_ii_lib.mux_dc.interface
--
-- created:
--          by - lspetrck.meyer (pc086)
--          at - 16:46:35 05/24/22
--
-- generated by mentor graphics' hdl designer(tm) 2020.2 built on 12 apr 2020 at 11:28:22
--
library ieee;
use ieee.std_logic_1164.all;
library raro_ikr_risc_ii_lib;
use raro_ikr_risc_ii_lib.internal_types.all;
use raro_ikr_risc_ii_lib.isa_types.all;

entity mux_dc is
   port( 
      a_imm    : in     word;
      rf_mux_a : in     word;
      sel_imm  : in     std_logic;
      ra_in    : out    word
   );

-- declarations

end mux_dc ;

