-- vhdl entity raro_ikr_risc_ii_lib.mux_clock.interface
--
-- created:
--          by - lspetrck.meyer (pc091)
--          at - 15:21:04 07/15/22
--
-- generated by mentor graphics' hdl designer(tm) 2020.2 built on 12 apr 2020 at 11:28:22
--
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
library raro_ikr_risc_ii_lib;
use raro_ikr_risc_ii_lib.internal_types.all;use raro_ikr_risc_ii_lib.isa_types.all;

entity mux_clock is
   port( 
      man_clk : in     std_logic;
      res_n   : in     std_logic;
      sel_clk : in     std_logic;
      std_clk : in     std_logic;
      clk     : out    std_logic
   );

-- declarations

end mux_clock ;

