-- VHDL Entity raro_ikr_risc_II_lib.raro_ikr_risc_II.symbol
--
-- Created:
--          by - lspetrck.meyer (pc091)
--          at - 15:21:04 07/15/22
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2020.2 Built on 12 Apr 2020 at 11:28:22
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;

LIBRARY raro_ikr_risc_II_lib;
USE raro_ikr_risc_II_lib.internal_types.all;

ENTITY raro_ikr_risc_II IS
   PORT( 
      man_clk : IN     std_logic;
      res_n   : IN     std_logic;
      sel_clk : IN     std_logic;
      std_clk : IN     std_logic;
      survive : OUT    word
   );

-- Declarations

END raro_ikr_risc_II ;

