-- vhdl entity raro_ikr_risc_ii_lib.raro_ikr_risc_ii.symbol
--
-- created:
--          by - lspetrck.meyer (pc091)
--          at - 15:21:04 07/15/22
--
-- generated by mentor graphics' hdl designer(tm) 2020.2 built on 12 apr 2020 at 11:28:22
--
library ieee;
use ieee.std_logic_1164.all;

library raro_ikr_risc_ii_lib;
use raro_ikr_risc_ii_lib.internal_types.all;

entity raro_ikr_risc_ii is
   port( 
      man_clk : in     std_logic;
      res_n   : in     std_logic;
      sel_clk : in     std_logic;
      std_clk : in     std_logic;
      survive : out    word
   );

-- declarations

end raro_ikr_risc_ii ;

