--
-- VHDL Architecture raro_ikr_risc_II_lib.raro_ikr_risc_II_tb.struct
--
-- Created:
--          by - kntntply.meyer (pc091)
--          at - 17:31:49 07/13/22
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2020.2 Built on 12 Apr 2020 at 11:28:22
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;

LIBRARY raro_ikr_risc_II_lib;
USE raro_ikr_risc_II_lib.internal_types.ALL;


ARCHITECTURE struct OF raro_ikr_risc_II_tb IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL man_clk : std_logic;
   SIGNAL res_n   : std_logic;
   SIGNAL sel_clk : std_logic;
   SIGNAL std_clk : std_logic;


   -- Component Declarations
   COMPONENT clk_res_gen
   PORT (
      res_n   : OUT    std_logic ;
      std_clk : OUT    std_logic 
   );
   END COMPONENT;
   COMPONENT man_clk_sim
   PORT (
      man_clk : OUT    std_logic ;
      sel_clk : OUT    std_logic 
   );
   END COMPONENT;
   COMPONENT raro_ikr_risc_II
   PORT (
      man_clk : IN     std_logic ;
      res_n   : IN     std_logic ;
      sel_clk : IN     std_logic ;
      std_clk : IN     std_logic ;
      survive : OUT    word 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : clk_res_gen USE ENTITY raro_ikr_risc_II_lib.clk_res_gen;
   FOR ALL : man_clk_sim USE ENTITY raro_ikr_risc_II_lib.man_clk_sim;
   FOR ALL : raro_ikr_risc_II USE ENTITY raro_ikr_risc_II_lib.raro_ikr_risc_II;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   U_1 : clk_res_gen
      PORT MAP (
         res_n   => res_n,
         std_clk => std_clk
      );
   U_2 : man_clk_sim
      PORT MAP (
         man_clk => man_clk,
         sel_clk => sel_clk
      );
   U_0 : raro_ikr_risc_II
      PORT MAP (
         man_clk => man_clk,
         res_n   => res_n,
         sel_clk => sel_clk,
         std_clk => std_clk,
         survive => OPEN
      );

END struct;
