--
-- VHDL Architecture raro_ikr_risc_II_lib.raro_ikr_risc_II_tb.struct
--
-- Created:
--          by - lspetrck.meyer (pc091)
--          at - 17:22:06 05/25/22
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2020.2 Built on 12 Apr 2020 at 11:28:22
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;

LIBRARY raro_ikr_risc_II_lib;

ARCHITECTURE struct OF raro_ikr_risc_II_tb IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL clk   : std_logic;
   SIGNAL res_n : std_logic;


   -- Component Declarations
   COMPONENT clk_res_gen
   PORT (
      clk   : OUT    std_logic ;
      res_n : OUT    std_logic 
   );
   END COMPONENT;
   COMPONENT raro_ikr_risc_II
   PORT (
      clk   : IN     std_logic ;
      res_n : IN     std_logic 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : clk_res_gen USE ENTITY raro_ikr_risc_II_lib.clk_res_gen;
   FOR ALL : raro_ikr_risc_II USE ENTITY raro_ikr_risc_II_lib.raro_ikr_risc_II;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   U_1 : clk_res_gen
      PORT MAP (
         clk   => clk,
         res_n => res_n
      );
   U_0 : raro_ikr_risc_II
      PORT MAP (
         clk   => clk,
         res_n => res_n
      );

END struct;
