--
-- VHDL Architecture raro_ikr_risc_II_lib.raro_ikr_risc_II.struct
--
-- Created:
--          by - lspetrck.meyer (pc091)
--          at - 14:29:26 05/18/22
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2020.2 Built on 12 Apr 2020 at 11:28:22
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
LIBRARY raro_ikr_risc_II_lib;
USE raro_ikr_risc_II_lib.internal_types.all;


ARCHITECTURE struct OF raro_ikr_risc_II IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL rALU_in        : std_logic_vector(15 DOWNTO 0);
   SIGNAL rALU_out       : std_logic_vector(15 DOWNTO 0);
   SIGNAL rA_in          : std_logic_vector(15 DOWNTO 0);
   SIGNAL rA_out         : std_logic_vector(15 DOWNTO 0);
   SIGNAL rB_in          : std_logic_vector(15 DOWNTO 0);
   SIGNAL rB_out         : std_logic_vector(15 DOWNTO 0);
   SIGNAL rC_in          : std_logic_vector(15 DOWNTO 0);
   SIGNAL rC_out         : std_logic_vector(15 DOWNTO 0);
   SIGNAL rME_in         : std_logic_vector(15 DOWNTO 0);
   SIGNAL rME_out        : std_logic_vector(15 DOWNTO 0);
   SIGNAL rNextPC_out    : std_logic_vector(15 DOWNTO 0);
   SIGNAL rNextPc_in     : word;
   SIGNAL rOpcode_in     : word;
   SIGNAL rOpcode_out    : word;
   SIGNAL rPc_in         : word;
   SIGNAL rPc_out        : word;
   SIGNAL rStoreData_in  : std_logic_vector(15 DOWNTO 0);
   SIGNAL rStoreData_out : std_logic_vector(15 DOWNTO 0);


   -- Component Declarations
   COMPONENT mux_init
   PORT (
      rPc_out : IN     word ;
      rPc_in  : OUT    word 
   );
   END COMPONENT;
   COMPONENT reg_dc_ex
   PORT (
      rA_in       : IN     std_logic_vector (15 DOWNTO 0);
      rB_in       : IN     std_logic_vector (15 DOWNTO 0);
      rC_in       : IN     std_logic_vector (15 DOWNTO 0);
      rNextPc_in  : IN     word;
      rA_out      : OUT    std_logic_vector (15 DOWNTO 0);
      rB_out      : OUT    std_logic_vector (15 DOWNTO 0);
      rC_out      : OUT    std_logic_vector (15 DOWNTO 0);
      rNextPC_out : OUT    std_logic_vector (15 DOWNTO 0)
   );
   END COMPONENT;
   COMPONENT reg_if_dc
   PORT (
      clk         : IN     std_logic ;
      rOpcode_in  : IN     word ;
      rPc_in      : IN     word ;
      res_n       : IN     std_logic ;
      rNextPc_in  : OUT    word ;
      rOpcode_out : OUT    word 
   );
   END COMPONENT;
   COMPONENT reg_me_wb
   PORT (
      rME_in  : IN     std_logic_vector (15 DOWNTO 0);
      rME_out : OUT    std_logic_vector (15 DOWNTO 0)
   );
   END COMPONENT;
   COMPONENT reg_mx_me
   PORT (
      rALU_in        : IN     std_logic_vector (15 DOWNTO 0);
      rStoreData_in  : IN     std_logic_vector (15 DOWNTO 0);
      rALU_out       : OUT    std_logic_vector (15 DOWNTO 0);
      rStoreData_out : OUT    std_logic_vector (15 DOWNTO 0)
   );
   END COMPONENT;
   COMPONENT reg_pc
   PORT (
      clk     : IN     std_logic ;
      rPc_in  : IN     word ;
      res_n   : IN     std_logic ;
      rPc_out : OUT    word 
   );
   END COMPONENT;
   COMPONENT step_dc
   PORT (
      rME_out : IN     std_logic_vector (15 DOWNTO 0);
      rA_in   : OUT    std_logic_vector (15 DOWNTO 0);
      rB_in   : OUT    std_logic_vector (15 DOWNTO 0);
      rC_in   : OUT    std_logic_vector (15 DOWNTO 0)
   );
   END COMPONENT;
   COMPONENT step_ex
   PORT (
      rA_out        : IN     std_logic_vector (15 DOWNTO 0);
      rB_out        : IN     std_logic_vector (15 DOWNTO 0);
      rC_out        : IN     std_logic_vector (15 DOWNTO 0);
      rNextPC_out   : IN     std_logic_vector (15 DOWNTO 0);
      rALU_in       : OUT    std_logic_vector (15 DOWNTO 0);
      rStoreData_in : OUT    std_logic_vector (15 DOWNTO 0)
   );
   END COMPONENT;
   COMPONENT step_if
   PORT (
      rPc_out    : IN     word ;
      rOpcode_in : OUT    word 
   );
   END COMPONENT;
   COMPONENT step_me
   PORT (
      rALU_out       : IN     std_logic_vector (15 DOWNTO 0);
      rStoreData_out : IN     std_logic_vector (15 DOWNTO 0);
      rME_in         : OUT    std_logic_vector (15 DOWNTO 0)
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : mux_init USE ENTITY raro_ikr_risc_II_lib.mux_init;
   FOR ALL : reg_dc_ex USE ENTITY raro_ikr_risc_II_lib.reg_dc_ex;
   FOR ALL : reg_if_dc USE ENTITY raro_ikr_risc_II_lib.reg_if_dc;
   FOR ALL : reg_me_wb USE ENTITY raro_ikr_risc_II_lib.reg_me_wb;
   FOR ALL : reg_mx_me USE ENTITY raro_ikr_risc_II_lib.reg_mx_me;
   FOR ALL : reg_pc USE ENTITY raro_ikr_risc_II_lib.reg_pc;
   FOR ALL : step_dc USE ENTITY raro_ikr_risc_II_lib.step_dc;
   FOR ALL : step_ex USE ENTITY raro_ikr_risc_II_lib.step_ex;
   FOR ALL : step_if USE ENTITY raro_ikr_risc_II_lib.step_if;
   FOR ALL : step_me USE ENTITY raro_ikr_risc_II_lib.step_me;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   U_0 : mux_init
      PORT MAP (
         rPc_out => rPc_out,
         rPc_in  => rPc_in
      );
   U_6 : reg_dc_ex
      PORT MAP (
         rA_in       => rA_in,
         rB_in       => rB_in,
         rC_in       => rC_in,
         rNextPc_in  => rNextPc_in,
         rA_out      => rA_out,
         rB_out      => rB_out,
         rC_out      => rC_out,
         rNextPC_out => rNextPC_out
      );
   U_4 : reg_if_dc
      PORT MAP (
         clk         => clk,
         rOpcode_in  => rOpcode_in,
         rPc_in      => rPc_in,
         res_n       => res_n,
         rNextPc_in  => rNextPc_in,
         rOpcode_out => rOpcode_out
      );
   U_11 : reg_me_wb
      PORT MAP (
         rME_in  => rME_in,
         rME_out => rME_out
      );
   U_8 : reg_mx_me
      PORT MAP (
         rALU_in        => rALU_in,
         rStoreData_in  => rStoreData_in,
         rALU_out       => rALU_out,
         rStoreData_out => rStoreData_out
      );
   U_2 : reg_pc
      PORT MAP (
         clk     => clk,
         rPc_in  => rPc_in,
         res_n   => res_n,
         rPc_out => rPc_out
      );
   U_5 : step_dc
      PORT MAP (
         rME_out => rME_out,
         rA_in   => rA_in,
         rB_in   => rB_in,
         rC_in   => rC_in
      );
   U_7 : step_ex
      PORT MAP (
         rA_out        => rA_out,
         rB_out        => rB_out,
         rC_out        => rC_out,
         rNextPC_out   => rNextPC_out,
         rALU_in       => rALU_in,
         rStoreData_in => rStoreData_in
      );
   U_3 : step_if
      PORT MAP (
         rPc_out    => rPc_out,
         rOpcode_in => rOpcode_in
      );
   U_9 : step_me
      PORT MAP (
         rALU_out       => rALU_out,
         rStoreData_out => rStoreData_out,
         rME_in         => rME_in
      );

END struct;
