--
-- vhdl architecture raro_ikr_risc_ii_lib.raro_ikr_risc_ii_tb.struct
--
-- created:
--          by - kntntply.meyer (pc091)
--          at - 17:31:49 07/13/22
--
-- generated by mentor graphics' hdl designer(tm) 2020.2 built on 12 apr 2020 at 11:28:22
--
library ieee;
use ieee.std_logic_1164.all;

library raro_ikr_risc_ii_lib;
use raro_ikr_risc_ii_lib.internal_types.all;


architecture struct of raro_ikr_risc_ii_tb is

   -- architecture declarations

   -- internal signal declarations
   signal man_clk : std_logic;
   signal res_n   : std_logic;
   signal sel_clk : std_logic;
   signal std_clk : std_logic;


   -- component declarations
   component clk_res_gen
   port (
      res_n   : out    std_logic ;
      std_clk : out    std_logic 
   );
   end component;
   component man_clk_sim
   port (
      man_clk : out    std_logic ;
      sel_clk : out    std_logic 
   );
   end component;
   component raro_ikr_risc_ii
   port (
      man_clk : in     std_logic ;
      res_n   : in     std_logic ;
      sel_clk : in     std_logic ;
      std_clk : in     std_logic ;
      survive : out    word 
   );
   end component;

   -- optional embedded configurations
   -- pragma synthesis_off
   for all : clk_res_gen use entity raro_ikr_risc_ii_lib.clk_res_gen;
   for all : man_clk_sim use entity raro_ikr_risc_ii_lib.man_clk_sim;
   for all : raro_ikr_risc_ii use entity raro_ikr_risc_ii_lib.raro_ikr_risc_ii;
   -- pragma synthesis_on


begin

   -- instance port mappings.
   u_1 : clk_res_gen
      port map (
         res_n   => res_n,
         std_clk => std_clk
      );
   u_2 : man_clk_sim
      port map (
         man_clk => man_clk,
         sel_clk => sel_clk
      );
   u_0 : raro_ikr_risc_ii
      port map (
         man_clk => man_clk,
         res_n   => res_n,
         sel_clk => sel_clk,
         std_clk => std_clk,
         survive => open
      );

end struct;
