-- VHDL Entity raro_ikr_risc_II_lib.raro_ikr_risc_II.symbol
--
-- Created:
--          by - lspetrck.meyer (pc091)
--          at - 14:29:26 05/18/22
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2020.2 Built on 12 Apr 2020 at 11:28:22
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;

ENTITY raro_ikr_risc_II IS
   PORT( 
      clk   : IN     std_logic;
      res_n : IN     std_logic
   );

-- Declarations

END raro_ikr_risc_II ;

