-- VHDL Entity raro_ikr_risc_II_lib.reg_dc_ex.interface
--
-- Created:
--          by - lspetrck.meyer (pc091)
--          at - 17:23:08 05/18/22
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2020.2 Built on 12 Apr 2020 at 11:28:22
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
LIBRARY raro_ikr_risc_II_lib;
USE raro_ikr_risc_II_lib.internal_types.all;

ENTITY reg_dc_ex IS
   PORT( 
      clk            : IN     std_logic;
      rA_in          : IN     word;
      rB_in          : IN     word;
      rC_in          : IN     word;
      rNextPc_in_dc  : IN     word;
      res_n          : IN     std_logic;
      rA_out         : OUT    word;
      rB_out         : OUT    word;
      rC_out         : OUT    word;
      rNextPC_out_ex : OUT    word
   );

-- Declarations

END reg_dc_ex ;

