-- VHDL Entity raro_ikr_risc_II_lib.reg_dc.interface
--
-- Created:
--          by - lspetrck.meyer (pc091)
--          at - 18:37:10 05/11/22
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2020.2 Built on 12 Apr 2020 at 11:28:22
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
LIBRARY raro_ikr_risc_II_lib;
USE raro_ikr_risc_II_lib.internal_types.all;

ENTITY reg_dc IS
   PORT( 
      clk              : IN     std_logic;
      dc_in_rOpcode    : IN     word;
      if_in_rPc        : IN     word;
      res_n            : IN     std_logic;
      dc_inOut_rNextPc : OUT    word;
      dc_out_rOpcode   : OUT    word
   );

-- Declarations

END reg_dc ;

