-- VHDL Entity raro_ikr_risc_II_lib.reg_ex.generatedInstance
--
-- Created:
--          by - lspetrck.meyer (pc091)
--          at - 18:37:10 05/11/22
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2020.2 Built on 12 Apr 2020 at 11:28:22
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
LIBRARY raro_ikr_risc_II_lib;
USE raro_ikr_risc_II_lib.internal_types.all;

ENTITY reg_ex IS
   PORT( 
      dc_inOut_rNextPc : IN     word;
      ex_in_ra         : IN     std_logic_vector (15 DOWNTO 0);
      ex_in_rb         : IN     std_logic_vector (15 DOWNTO 0);
      ex_in_rc         : IN     std_logic_vector (15 DOWNTO 0);
      ex_out_nextPc    : OUT    std_logic_vector (15 DOWNTO 0);
      ex_out_ra        : OUT    std_logic_vector (15 DOWNTO 0);
      ex_out_rb        : OUT    std_logic_vector (15 DOWNTO 0);
      ex_out_rc        : OUT    std_logic_vector (15 DOWNTO 0)
   );

END reg_ex ;

