-- VHDL Entity raro_ikr_risc_II_lib.reg_mx_me.generatedInstance
--
-- Created:
--          by - lspetrck.meyer (pc091)
--          at - 14:29:26 05/18/22
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2020.2 Built on 12 Apr 2020 at 11:28:22
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
LIBRARY raro_ikr_risc_II_lib;
USE raro_ikr_risc_II_lib.internal_types.all;

ENTITY reg_mx_me IS
   PORT( 
      rALU_in        : IN     std_logic_vector (15 DOWNTO 0);
      rALU_out       : OUT    std_logic_vector (15 DOWNTO 0);
      rStoreData_in  : IN     std_logic_vector (15 DOWNTO 0);
      rStoreData_out : OUT    std_logic_vector (15 DOWNTO 0)
   );

END reg_mx_me ;

