-- VHDL Entity raro_ikr_risc_II_lib.reg_dc_ex.generatedInstance
--
-- Created:
--          by - lspetrck.meyer (pc091)
--          at - 16:18:31 05/18/22
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2020.2 Built on 12 Apr 2020 at 11:28:22
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
LIBRARY raro_ikr_risc_II_lib;
USE raro_ikr_risc_II_lib.internal_types.all;

ENTITY reg_dc_ex IS
   PORT( 
      rA_in       : IN     word;
      rA_out      : OUT    word;
      rB_in       : IN     word;
      rB_out      : OUT    word;
      rC_in       : IN     word;
      rC_out      : OUT    word;
      rNextPc_in  : IN     word;
      rNextPC_out : OUT    word
   );

END reg_dc_ex ;

