-- VHDL Entity raro_ikr_risc_II_lib.reg_me_wb.interface
--
-- Created:
--          by - lspetrck.meyer (pc091)
--          at - 14:58:26 05/25/22
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2020.2 Built on 12 Apr 2020 at 11:28:22
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;
LIBRARY raro_ikr_risc_II_lib;
USE raro_ikr_risc_II_lib.internal_types.all;USE raro_ikr_risc_II_lib.isa_types.ALL;

ENTITY reg_me_wb IS
   PORT( 
      clk               : IN     std_logic;
      rME_in            : IN     word;
      rTargetReg_out_me : IN     reg_addr_type;
      res_n             : IN     std_logic;
      rME_out           : OUT    word;
      rTargetReg_out_wb : OUT    reg_addr_type
   );

-- Declarations

END reg_me_wb ;

