-- VHDL Entity raro_ikr_risc_II_lib.reg_mx_me.interface
--
-- Created:
--          by - lspetrck.meyer (pc086)
--          at - 18:07:42 05/24/22
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2020.2 Built on 12 Apr 2020 at 11:28:22
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
LIBRARY raro_ikr_risc_II_lib;
USE raro_ikr_risc_II_lib.internal_types.all;USE raro_ikr_risc_II_lib.isa_types.ALL;

ENTITY reg_mx_me IS
   PORT( 
      clk            : IN     std_logic;
      rALU_in        : IN     word;
      rStoreData_in  : IN     word;
      res_n          : IN     std_logic;
      rALU_out       : OUT    word;
      rStoreData_out : OUT    word
   );

-- Declarations

END reg_mx_me ;

