-- vhdl entity raro_ikr_risc_ii_lib.reg_ex_me.generatedinstance
--
-- created:
--          by - kntntply.meyer (pc091)
--          at - 16:15:37 07/13/22
--
-- generated by mentor graphics' hdl designer(tm) 2020.2 built on 12 apr 2020 at 11:28:22
--
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
library raro_ikr_risc_ii_lib;
use raro_ikr_risc_ii_lib.internal_types.all;use raro_ikr_risc_ii_lib.isa_types.all;

entity reg_ex_me is
   port( 
      clk               : in     std_logic;
      ralu_in           : in     word;
      ralu_out          : out    word;
      res_n             : in     std_logic;
      rfwd_selsd_out_ex : in     fwd_mode_type;
      rfwd_selsd_out_me : out    fwd_mode_type;
      rmemmode_out_ex   : in     mem_mode_type;
      rmemmode_out_me   : out    mem_mode_type;
      rstoredata_in     : in     word;
      rstoredata_out    : out    word;
      rtargetreg_out_ex : in     reg_addr_type;
      rtargetreg_out_me : out    reg_addr_type
   );

end reg_ex_me ;

