-- VHDL Entity raro_ikr_risc_II_lib.reg_ex_me.generatedInstance
--
-- Created:
--          by - kntntply.meyer (pc091)
--          at - 16:15:37 07/13/22
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2020.2 Built on 12 Apr 2020 at 11:28:22
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;
LIBRARY raro_ikr_risc_II_lib;
USE raro_ikr_risc_II_lib.internal_types.all;USE raro_ikr_risc_II_lib.isa_types.ALL;

ENTITY reg_ex_me IS
   PORT( 
      clk               : IN     std_logic;
      rALU_in           : IN     word;
      rALU_out          : OUT    word;
      res_n             : IN     std_logic;
      rFwd_selsd_out_ex : IN     fwd_mode_type;
      rFwd_selsd_out_me : OUT    fwd_mode_type;
      rMemMode_out_ex   : IN     mem_mode_type;
      rMemMode_out_me   : OUT    mem_mode_type;
      rStoreData_in     : IN     word;
      rStoreData_out    : OUT    word;
      rTargetReg_out_ex : IN     reg_addr_type;
      rTargetReg_out_me : OUT    reg_addr_type
   );

END reg_ex_me ;

