-- VHDL Entity raro_ikr_risc_II_lib.reg_dc_ex.interface
--
-- Created:
--          by - lspetrck.meyer (pc091)
--          at - 14:37:14 06/15/22
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2020.2 Built on 12 Apr 2020 at 11:28:22
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;
LIBRARY raro_ikr_risc_II_lib;
USE raro_ikr_risc_II_lib.internal_types.all;USE raro_ikr_risc_II_lib.isa_types.ALL;

ENTITY reg_dc_ex IS
   PORT( 
      clk               : IN     std_logic;
      rA_in             : IN     word;
      rAluMode_in       : IN     alu_mode_type;
      rB_in             : IN     word;
      rC_in             : IN     word;
      rFwd_sela_in_dc   : IN     fwd_mode_type;
      rFwd_selb_in_dc   : IN     fwd_mode_type;
      rFwd_selc_in_dc   : IN     fwd_mode_type;
      rFwd_selsd_in_dc  : IN     fwd_mode_type;
      rMemMode_in_dc    : IN     mem_mode_type;
      rNextPc_in_dc     : IN     word;
      rTargetReg_in_dc  : IN     reg_addr_type;
      res_n             : IN     std_logic;
      sbpu_PC           : IN     word;
      rA_out            : OUT    word;
      rAluMode_out      : OUT    alu_mode_type;
      rB_out            : OUT    word;
      rC_out            : OUT    word;
      rFwd_sela_out_ex  : OUT    fwd_mode_type;
      rFwd_selb_out_ex  : OUT    fwd_mode_type;
      rFwd_selc_out_ex  : OUT    fwd_mode_type;
      rFwd_selsd_out_ex : OUT    fwd_mode_type;
      rMemMode_out_ex   : OUT    mem_mode_type;
      rNextPC_out_ex    : OUT    word;
      rTargetReg_out_ex : OUT    reg_addr_type
   );

-- Declarations

END reg_dc_ex ;

