-- vhdl entity raro_ikr_risc_ii_lib.reg_if_dc.interface
--
-- created:
--          by - kntntply.meyer (pc091)
--          at - 17:00:12 06/22/22
--
-- generated by mentor graphics' hdl designer(tm) 2020.2 built on 12 apr 2020 at 11:28:22
--
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
library raro_ikr_risc_ii_lib;
use raro_ikr_risc_ii_lib.internal_types.all;use raro_ikr_risc_ii_lib.isa_types.all;

entity reg_if_dc is
   port( 
      clk           : in     std_logic;
      ropcode_in    : in     word;
      rpc_in        : in     word;
      res_n         : in     std_logic;
      stall_dc      : in     std_logic;
      rnextpc_in_dc : out    word;
      ropcode_out   : out    word
   );

-- declarations

end reg_if_dc ;

