-- vhdl entity raro_ikr_risc_ii_lib.reg_wb.generatedinstance
--
-- created:
--          by - lspetrck.meyer (pc091)
--          at - 18:37:10 05/11/22
--
-- generated by mentor graphics' hdl designer(tm) 2020.2 built on 12 apr 2020 at 11:28:22
--
library ieee;
use ieee.std_logic_1164.all;
library raro_ikr_risc_ii_lib;
use raro_ikr_risc_ii_lib.internal_types.all;

entity reg_wb is
   port( 
      wb_in_rmeout : in     std_logic_vector (15 downto 0);
      wb_out_sdc   : out    std_logic_vector (15 downto 0)
   );

end reg_wb ;

