-- vhdl entity raro_ikr_risc_ii_lib.reg_me.generatedinstance
--
-- created:
--          by - lspetrck.meyer (pc091)
--          at - 18:37:10 05/11/22
--
-- generated by mentor graphics' hdl designer(tm) 2020.2 built on 12 apr 2020 at 11:28:22
--
library ieee;
use ieee.std_logic_1164.all;
library raro_ikr_risc_ii_lib;
use raro_ikr_risc_ii_lib.internal_types.all;

entity reg_me is
   port( 
      me_in_raluout     : in     std_logic_vector (15 downto 0);
      me_in_rstoredata  : in     std_logic_vector (15 downto 0);
      me_out_raluout    : out    std_logic_vector (15 downto 0);
      me_out_rstoredata : out    std_logic_vector (15 downto 0)
   );

end reg_me ;

