-- vhdl entity raro_ikr_risc_ii_lib.rf_dc.interface
--
-- created:
--          by - lspetrck.meyer (pc091)
--          at - 14:55:05 05/25/22
--
-- generated by mentor graphics' hdl designer(tm) 2020.2 built on 12 apr 2020 at 11:28:22
--
library ieee;
use ieee.std_logic_1164.all;
library raro_ikr_risc_ii_lib;
use raro_ikr_risc_ii_lib.internal_types.all;
use raro_ikr_risc_ii_lib.isa_types.all;

entity rf_dc is
   port( 
      clk               : in     std_logic;
      rme_out           : in     word;
      rtargetreg_out_wb : in     reg_addr_type;
      res_n             : in     std_logic;
      sel_a             : in     reg_addr_type;
      sel_b             : in     reg_addr_type;
      sel_c             : in     reg_addr_type;
      rb_in             : out    word;
      rc_in             : out    word;
      rf_mux_a          : out    word
   );

-- declarations

end rf_dc ;

