-- VHDL Entity raro_ikr_risc_II_lib.RF_dc.interface
--
-- Created:
--          by - lspetrck.meyer (pc091)
--          at - 16:26:11 05/18/22
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2020.2 Built on 12 Apr 2020 at 11:28:22
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
LIBRARY raro_ikr_risc_II_lib;
USE raro_ikr_risc_II_lib.internal_types.ALL;
USE raro_ikr_risc_II_lib.isa_types.ALL;

ENTITY RF_dc IS
   PORT( 
      clk          : IN     std_logic;
      rME_out      : IN     word;
      res_n        : IN     std_logic;
      sel_a        : IN     std_logic_vector (4 DOWNTO 0);
      sel_b        : IN     std_logic_vector (4 DOWNTO 0);
      sel_c        : IN     std_logic_vector (4 DOWNTO 0);
      targetreg_wb : IN     word;
      rB_in        : OUT    word;
      rC_in        : OUT    word;
      rf_mux_a     : OUT    word
   );

-- Declarations

END RF_dc ;

