-- vhdl entity raro_ikr_risc_ii_lib.sbpu.interface
--
-- created:
--          by - lspetrck.meyer (pc091)
--          at - 14:37:14 06/15/22
--
-- generated by mentor graphics' hdl designer(tm) 2020.2 built on 12 apr 2020 at 11:28:22
--
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
library raro_ikr_risc_ii_lib;
use raro_ikr_risc_ii_lib.internal_types.all;use raro_ikr_risc_ii_lib.isa_types.all;

entity sbpu is
   port( 
      disp          : in     word;
      rnextpc_in_dc : in     word;
      sbpu_mode     : in     sbpu_mode_type;
      rsbpu_pc_in   : out    word;
      sbta_valid    : out    std_logic
   );

-- declarations

end sbpu ;

