--
-- vhdl architecture raro_ikr_risc_ii_lib.step_ex.struct
--
-- created:
--          by - kntntply.meyer (pc091)
--          at - 16:00:32 06/22/22
--
-- generated by mentor graphics' hdl designer(tm) 2020.2 built on 12 apr 2020 at 11:28:22
--
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
library raro_ikr_risc_ii_lib;
use raro_ikr_risc_ii_lib.isa_types.all;
use raro_ikr_risc_ii_lib.internal_types.all;


architecture struct of step_ex is

   -- architecture declarations

   -- internal signal declarations
   signal alu_out   : word;
   signal mux_alu_a : word;

   -- implicit buffer signal declarations
   signal mux_alu_b_internal : word;


   -- component declarations
   component alu_ex
   port (
      mux_alu_a    : in     word ;
      mux_alu_b    : in     word ;
      ralumode_out : in     alu_mode_type ;
      alu_out      : out    word 
   );
   end component;
   component mux_ex_1
   port (
      ralu_out         : in     word ;
      ra_out           : in     word ;
      rfwd_sela_out_ex : in     fwd_mode_type ;
      rme_out          : in     word ;
      mux_alu_a        : out    word 
   );
   end component;
   component mux_ex_2
   port (
      ralu_out         : in     word ;
      rb_out           : in     word ;
      rfwd_selb_out_ex : in     fwd_mode_type ;
      rme_out          : in     word ;
      mux_alu_b        : out    word 
   );
   end component;
   component mux_ex_3
   port (
      ralu_out         : in     word ;
      rc_out           : in     word ;
      rfwd_selc_out_ex : in     fwd_mode_type ;
      rme_out          : in     word ;
      rstoredata_in    : out    word 
   );
   end component;
   component mux_ex_4
   port (
      alu_out        : in     word ;
      rnextpc_out_ex : in     word ;
      sel_alu_pc     : in     std_logic ;
      ralu_in        : out    word 
   );
   end component;

   -- optional embedded configurations
   -- pragma synthesis_off
   for all : alu_ex use entity raro_ikr_risc_ii_lib.alu_ex;
   for all : mux_ex_1 use entity raro_ikr_risc_ii_lib.mux_ex_1;
   for all : mux_ex_2 use entity raro_ikr_risc_ii_lib.mux_ex_2;
   for all : mux_ex_3 use entity raro_ikr_risc_ii_lib.mux_ex_3;
   for all : mux_ex_4 use entity raro_ikr_risc_ii_lib.mux_ex_4;
   -- pragma synthesis_on


begin

   -- instance port mappings.
   u_4 : alu_ex
      port map (
         mux_alu_a    => mux_alu_a,
         mux_alu_b    => mux_alu_b_internal,
         ralumode_out => ralumode_out,
         alu_out      => alu_out
      );
   u_0 : mux_ex_1
      port map (
         ralu_out         => ralu_out,
         ra_out           => ra_out,
         rfwd_sela_out_ex => rfwd_sela_out_ex,
         rme_out          => rme_out,
         mux_alu_a        => mux_alu_a
      );
   u_1 : mux_ex_2
      port map (
         ralu_out         => ralu_out,
         rb_out           => rb_out,
         rfwd_selb_out_ex => rfwd_selb_out_ex,
         rme_out          => rme_out,
         mux_alu_b        => mux_alu_b_internal
      );
   u_2 : mux_ex_3
      port map (
         ralu_out         => ralu_out,
         rc_out           => rc_out,
         rfwd_selc_out_ex => rfwd_selc_out_ex,
         rme_out          => rme_out,
         rstoredata_in    => rstoredata_in
      );
   u_3 : mux_ex_4
      port map (
         alu_out        => alu_out,
         rnextpc_out_ex => rnextpc_out_ex,
         sel_alu_pc     => sel_alu_pc,
         ralu_in        => ralu_in
      );

   -- implicit buffered output assignments
   mux_alu_b <= mux_alu_b_internal;

end struct;
