-- vhdl entity raro_ikr_risc_ii_lib.step_if.interface
--
-- created:
--          by - lspetrck.meyer (pc086)
--          at - 16:55:25 05/24/22
--
-- generated by mentor graphics' hdl designer(tm) 2020.2 built on 12 apr 2020 at 11:28:22
--
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
library raro_ikr_risc_ii_lib;
use raro_ikr_risc_ii_lib.internal_types.all;use raro_ikr_risc_ii_lib.isa_types.all;

entity step_if is
   port( 
      dbta_valid : in     std_logic;
      rpc_out    : in     word;
      sbta_valid : in     std_logic;
      ropcode_in : out    word
   );

-- declarations

end step_if ;

