--
-- VHDL Architecture raro_ikr_risc_II_lib.step_dc.struct
--
-- Created:
--          by - lspetrck.meyer (pc091)
--          at - 16:56:14 05/18/22
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2020.2 Built on 12 Apr 2020 at 11:28:22
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
LIBRARY raro_ikr_risc_II_lib;
USE raro_ikr_risc_II_lib.internal_types.ALL;
USE raro_ikr_risc_II_lib.isa_types.ALL;


ARCHITECTURE struct OF step_dc IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL a_imm       : word;
   SIGNAL alu_mode_dc : alu_mode_type;
   SIGNAL rf_mux_a    : word;
   SIGNAL sel_a       : std_logic_vector(4 DOWNTO 0);
   SIGNAL sel_b       : std_logic_vector(4 DOWNTO 0);
   SIGNAL sel_c       : std_logic_vector(4 DOWNTO 0);


   -- Component Declarations
   COMPONENT DEC_dc
   PORT (
      rOpcode_out : IN     word ;
      a_imm       : OUT    word ;
      alu_mode_dc : OUT    alu_mode_type ;
      sel_a       : OUT    std_logic_vector (4 DOWNTO 0);
      sel_b       : OUT    std_logic_vector (4 DOWNTO 0);
      sel_c       : OUT    std_logic_vector (4 DOWNTO 0)
   );
   END COMPONENT;
   COMPONENT MUX_dc
   PORT (
      a_imm    : IN     word;
      rf_mux_a : IN     word;
      rA_in    : OUT    word
   );
   END COMPONENT;
   COMPONENT RF_dc
   PORT (
      clk          : IN     std_logic ;
      rME_out      : IN     word ;
      res_n        : IN     std_logic ;
      sel_a        : IN     std_logic_vector (4 DOWNTO 0);
      sel_b        : IN     std_logic_vector (4 DOWNTO 0);
      sel_c        : IN     std_logic_vector (4 DOWNTO 0);
      targetreg_wb : IN     word ;
      rB_in        : OUT    word ;
      rC_in        : OUT    word ;
      rf_mux_a     : OUT    word 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : DEC_dc USE ENTITY raro_ikr_risc_II_lib.DEC_dc;
   FOR ALL : MUX_dc USE ENTITY raro_ikr_risc_II_lib.MUX_dc;
   FOR ALL : RF_dc USE ENTITY raro_ikr_risc_II_lib.RF_dc;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   U_0 : DEC_dc
      PORT MAP (
         rOpcode_out => rOpcode_out,
         a_imm       => a_imm,
         alu_mode_dc => alu_mode_dc,
         sel_a       => sel_a,
         sel_b       => sel_b,
         sel_c       => sel_c
      );
   U_2 : MUX_dc
      PORT MAP (
         a_imm    => a_imm,
         rf_mux_a => rf_mux_a,
         rA_in    => rA_in
      );
   U_1 : RF_dc
      PORT MAP (
         clk          => clk,
         rME_out      => rME_out,
         res_n        => res_n,
         sel_a        => sel_a,
         sel_b        => sel_b,
         sel_c        => sel_c,
         targetreg_wb => targetreg_wb,
         rB_in        => rB_in,
         rC_in        => rC_in,
         rf_mux_a     => rf_mux_a
      );

END struct;
