-- vhdl entity raro_ikr_risc_ii_lib.step_dc.interface
--
-- created:
--          by - kntntply.meyer (pc091)
--          at - 13:50:07 07/06/22
--
-- generated by mentor graphics' hdl designer(tm) 2020.2 built on 12 apr 2020 at 11:28:22
--
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
library raro_ikr_risc_ii_lib;
use raro_ikr_risc_ii_lib.internal_types.all;use raro_ikr_risc_ii_lib.isa_types.all;

entity step_dc is
   port( 
      clk               : in     std_logic;
      dbta_valid        : in     std_logic;
      rme_out           : in     word;
      rmemmode_out_ex   : in     mem_mode_type;
      ropcode_out       : in     word;
      rtargetreg_out_ex : in     reg_addr_type;
      rtargetreg_out_me : in     reg_addr_type;
      rtargetreg_out_wb : in     reg_addr_type;
      res_n             : in     std_logic;
      disp              : out    word;
      ra_in             : out    word;
      ralumode_in       : out    alu_mode_type;
      rb_in             : out    word;
      rc_in             : out    word;
      rdbpu_mode_in     : out    dbpu_mode_type;
      rfwd_sela_in_dc   : out    fwd_mode_type;
      rfwd_selb_in_dc   : out    fwd_mode_type;
      rfwd_selc_in_dc   : out    fwd_mode_type;
      rfwd_selsd_in_dc  : out    fwd_mode_type;
      rmemmode_in_dc    : out    mem_mode_type;
      rtargetreg_in_dc  : out    reg_addr_type;
      sbpu_mode         : out    sbpu_mode_type;
      stall_dc          : out    std_logic
   );

-- declarations

end step_dc ;

