--
-- VHDL Architecture raro_ikr_risc_II_lib.step_ex.struct
--
-- Created:
--          by - lspetrck.meyer (pc091)
--          at - 12:08:28 06/15/22
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2020.2 Built on 12 Apr 2020 at 11:28:22
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;
LIBRARY raro_ikr_risc_II_lib;
USE raro_ikr_risc_II_lib.isa_types.ALL;
USE raro_ikr_risc_II_lib.internal_types.ALL;


ARCHITECTURE struct OF step_ex IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL ALU_out   : word;
   SIGNAL mux_ALU_A : word;
   SIGNAL mux_ALU_B : word;


   -- Component Declarations
   COMPONENT ALU_ex
   PORT (
      mux_ALU_A    : IN     word ;
      mux_ALU_B    : IN     word ;
      rAluMode_out : IN     alu_mode_type ;
      ALU_out      : OUT    word 
   );
   END COMPONENT;
   COMPONENT MUX_ex_1
   PORT (
      rALU_out         : IN     word ;
      rA_out           : IN     word ;
      rFwd_sela_out_ex : IN     fwd_mode_type ;
      rME_out          : IN     word ;
      mux_ALU_A        : OUT    word 
   );
   END COMPONENT;
   COMPONENT MUX_ex_2
   PORT (
      rALU_out         : IN     word ;
      rB_out           : IN     word ;
      rFwd_selb_out_ex : IN     fwd_mode_type ;
      rME_out          : IN     word ;
      mux_ALU_B        : OUT    word 
   );
   END COMPONENT;
   COMPONENT MUX_ex_3
   PORT (
      rALU_out         : IN     word ;
      rC_out           : IN     word ;
      rFwd_selc_out_ex : IN     fwd_mode_type ;
      rME_out          : IN     word ;
      rStoreData_in    : OUT    word 
   );
   END COMPONENT;
   COMPONENT MUX_ex_4
   PORT (
      ALU_out        : IN     word ;
      rNextPC_out_ex : IN     word ;
      rALU_in        : OUT    word 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : ALU_ex USE ENTITY raro_ikr_risc_II_lib.ALU_ex;
   FOR ALL : MUX_ex_1 USE ENTITY raro_ikr_risc_II_lib.MUX_ex_1;
   FOR ALL : MUX_ex_2 USE ENTITY raro_ikr_risc_II_lib.MUX_ex_2;
   FOR ALL : MUX_ex_3 USE ENTITY raro_ikr_risc_II_lib.MUX_ex_3;
   FOR ALL : MUX_ex_4 USE ENTITY raro_ikr_risc_II_lib.MUX_ex_4;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   U_4 : ALU_ex
      PORT MAP (
         mux_ALU_A    => mux_ALU_A,
         mux_ALU_B    => mux_ALU_B,
         rAluMode_out => rAluMode_out,
         ALU_out      => ALU_out
      );
   U_0 : MUX_ex_1
      PORT MAP (
         rALU_out         => rALU_out,
         rA_out           => rA_out,
         rFwd_sela_out_ex => rFwd_sela_out_ex,
         rME_out          => rME_out,
         mux_ALU_A        => mux_ALU_A
      );
   U_1 : MUX_ex_2
      PORT MAP (
         rALU_out         => rALU_out,
         rB_out           => rB_out,
         rFwd_selb_out_ex => rFwd_selb_out_ex,
         rME_out          => rME_out,
         mux_ALU_B        => mux_ALU_B
      );
   U_2 : MUX_ex_3
      PORT MAP (
         rALU_out         => rALU_out,
         rC_out           => rC_out,
         rFwd_selc_out_ex => rFwd_selc_out_ex,
         rME_out          => rME_out,
         rStoreData_in    => rStoreData_in
      );
   U_3 : MUX_ex_4
      PORT MAP (
         ALU_out        => ALU_out,
         rNextPC_out_ex => rNextPC_out_ex,
         rALU_in        => rALU_in
      );

END struct;
