--
-- VHDL Architecture raro_ikr_risc_II_lib.step_dc.struct
--
-- Created:
--          by - lspetrck.meyer (pc091)
--          at - 18:43:02 05/11/22
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2020.2 Built on 12 Apr 2020 at 11:28:22
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
LIBRARY raro_ikr_risc_II_lib;
USE raro_ikr_risc_II_lib.internal_types.ALL;


ARCHITECTURE struct OF step_dc IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL dc_out_rOpcode : word;
   SIGNAL dec_mux        : std_logic_vector(15 DOWNTO 0);
   SIGNAL dec_rf         : std_logic_vector(15 DOWNTO 0);
   SIGNAL dec_rf_a       : std_logic_vector(15 DOWNTO 0);
   SIGNAL dec_rf_b       : std_logic_vector(15 DOWNTO 0);
   SIGNAL dec_rf_c       : std_logic_vector(15 DOWNTO 0);
   SIGNAL ex_in_ra       : std_logic_vector(15 DOWNTO 0);
   SIGNAL ex_in_rb       : std_logic_vector(15 DOWNTO 0);
   SIGNAL ex_in_rc       : std_logic_vector(15 DOWNTO 0);
   SIGNAL wb_out_sDc     : std_logic_vector(15 DOWNTO 0);


   -- Component Declarations
   COMPONENT DEC_dc
   PORT (
      dc_out_rOpcode : IN     word;
      dec_mux        : OUT    std_logic_vector (15 DOWNTO 0);
      dec_rf_a       : OUT    std_logic_vector (15 DOWNTO 0);
      dec_rf_b       : OUT    std_logic_vector (15 DOWNTO 0);
      dec_rf_c       : OUT    std_logic_vector (15 DOWNTO 0)
   );
   END COMPONENT;
   COMPONENT MUX_dc
   PORT (
      dec_mux  : IN     std_logic_vector (15 DOWNTO 0);
      dec_rf   : IN     std_logic_vector (15 DOWNTO 0);
      ex_in_ra : OUT    std_logic_vector (15 DOWNTO 0)
   );
   END COMPONENT;
   COMPONENT RF_dc
   PORT (
      dec_rf_a   : IN     std_logic_vector (15 DOWNTO 0);
      dec_rf_b   : IN     std_logic_vector (15 DOWNTO 0);
      dec_rf_c   : IN     std_logic_vector (15 DOWNTO 0);
      wb_out_sDc : IN     std_logic_vector (15 DOWNTO 0);
      dec_rf     : OUT    std_logic_vector (15 DOWNTO 0);
      ex_in_rb   : OUT    std_logic_vector (15 DOWNTO 0);
      ex_in_rc   : OUT    std_logic_vector (15 DOWNTO 0)
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : DEC_dc USE ENTITY raro_ikr_risc_II_lib.DEC_dc;
   FOR ALL : MUX_dc USE ENTITY raro_ikr_risc_II_lib.MUX_dc;
   FOR ALL : RF_dc USE ENTITY raro_ikr_risc_II_lib.RF_dc;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   U_0 : DEC_dc
      PORT MAP (
         dc_out_rOpcode => dc_out_rOpcode,
         dec_mux        => dec_mux,
         dec_rf_a       => dec_rf_a,
         dec_rf_b       => dec_rf_b,
         dec_rf_c       => dec_rf_c
      );
   U_2 : MUX_dc
      PORT MAP (
         dec_mux  => dec_mux,
         dec_rf   => dec_rf,
         ex_in_ra => ex_in_ra
      );
   U_1 : RF_dc
      PORT MAP (
         dec_rf_a   => dec_rf_a,
         dec_rf_b   => dec_rf_b,
         dec_rf_c   => dec_rf_c,
         wb_out_sDc => wb_out_sDc,
         dec_rf     => dec_rf,
         ex_in_rb   => ex_in_rb,
         ex_in_rc   => ex_in_rc
      );

END struct;
