-- VHDL Entity raro_ikr_risc_II_lib.step_dc.interface
--
-- Created:
--          by - lspetrck.meyer (pc091)
--          at - 14:58:35 06/15/22
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2020.2 Built on 12 Apr 2020 at 11:28:22
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;
LIBRARY raro_ikr_risc_II_lib;
USE raro_ikr_risc_II_lib.internal_types.all;USE raro_ikr_risc_II_lib.isa_types.ALL;

ENTITY step_dc IS
   PORT( 
      clk               : IN     std_logic;
      rME_out           : IN     word;
      rMemMode_out_ex   : IN     mem_mode_type;
      rOpcode_out       : IN     word;
      rTargetReg_out_ex : IN     reg_addr_type;
      rTargetReg_out_me : IN     reg_addr_type;
      rTargetReg_out_wb : IN     reg_addr_type;
      res_n             : IN     std_logic;
      disp              : OUT    word;
      rA_in             : OUT    word;
      rAluMode_in       : OUT    alu_mode_type;
      rB_in             : OUT    word;
      rC_in             : OUT    word;
      rFwd_sela_in_dc   : OUT    fwd_mode_type;
      rFwd_selb_in_dc   : OUT    fwd_mode_type;
      rFwd_selc_in_dc   : OUT    fwd_mode_type;
      rFwd_selsd_in_dc  : OUT    fwd_mode_type;
      rMemMode_in_dc    : OUT    mem_mode_type;
      rTargetReg_in_dc  : OUT    reg_addr_type;
      sbpu_mode         : OUT    sbpu_mode_type;
      stall_dc          : OUT    std_logic
   );

-- Declarations

END step_dc ;

